### PR TITLE
Assisting the user when running qmake with the plugins in.

### PR DESCRIPTION
**Pull request by Maxzor**
What do you think of interacting with the user? It is not kconfig "make menuconfig" yet but well :)

### CODE REVIEW

**Comment by Maxzor** [comment]
I have almost finished a join solver rewrite.
Using preprocessor macros and this commit, people could choose to build the query builder without the automatic path module.

**Comment by rkhaotix** [comment]
Hmm... I don't know if I agree with this approach because for automated building processes (like linuxdeploy.sh) the script will be paused waiting for the user's interaction. Things can be worse if the building process is being run in a only CI/Build server where the user has no interaction with the shell.

Honestly, just warn the user about the absence of deps is enough. Oh, and a well written README file is also a good idea (yours seems good enough). :)

**Comment by Maxzor** [comment]
I agree this should not disturb packagers, build farms, and the likes.
You can flag in the qmake command CONFIG+=NON_INTERACTIVE_QMAKE and it is exactly like before.
I think such an interaction can help people feel they are a bit more not alone...

**Comment by Maxzor** [comment]
Will PR with the feature the other way later.

**Pull request closed without merging**
